version: 1

update_configs:
  - package_manager: "python"
    directory: "."
    update_schedule: "live"
    default_reviewers:
    - shunkakinoki

  - package_manager: "github_actions"
    directory: "."
    update_schedule: "daily"
    default_reviewers:
    - shunkakinoki

  - package_manager: "rust:cargo"
    directory: "."
    update_schedule: "live"
    default_reviewers:
    - shunkakinoki
