name: Cpplint
on:
  pull_request:
    paths:
      - "**.cpp"
      - "Pipfile"
      - "Pipfile.lock"
jobs:
  cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies with pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv sync --dev
      - name: Run test with Tox
        run: |
          pipenv run tox -e cpplint
      - name: Label on PR
        uses: awact/label-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "gha-cpp"
