name: Rust
on:
  push:
    branches:
      - master
    paths:
      - "**.rs"
  pull_request:
    paths:
      - "**.rs"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: icepuma/rust-action@master
        with:
          args: cargo fmt -- --check && cargo clippy -- -D warnings
